"""empty message

Revision ID: 28f77ead8cfa
Revises: 
Create Date: 2023-07-30 00:20:54.252668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '28f77ead8cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('inventory',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('order_size', sa.Integer(), nullable=False),
    sa.Column('order_cost', sa.Float(), nullable=False),
    sa.Column('order_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('pricing',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('design_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('revenue',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sale_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tob_event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('sale_id', 'product_id')
    )
    op.create_table('sales_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sales_rules')
    op.drop_table('revenue')
    op.drop_table('pricing')
    op.drop_table('inventory')
    op.drop_table('expenses')
    # ### end Alembic commands ###
